# when we lost all hills

class Scents_no_hill():

	ENEMY_HILL_SCENT_VALUE = 4000
	ENEMY_HILL_R1_SCENT_VALUE = 3900
	ENEMY_HILL_R2_SCENT_VALUE = 3800
	FOOD_SCENT_VALUE = 0
	UNSEEN_SCENT_VALUE = 300		
	INVISIBLE_SCENT_VALUE = 1		

	ENEMY_SCENT_VALUE = 0
	ENEMY_NEAR_OWN_HILL_SCENT_VALUE = 0
	ENEMY_AT_OWN_HILL_SCENT_VALUE = 0