# when we have few ants

class Scents_few_ants():

	ENEMY_HILL_SCENT_VALUE = 3000
	ENEMY_HILL_R1_SCENT_VALUE = 2900
	ENEMY_HILL_R2_SCENT_VALUE = 2800
	FOOD_SCENT_VALUE = 500
	UNSEEN_SCENT_VALUE = 75		
	INVISIBLE_SCENT_VALUE = 50		

	ENEMY_SCENT_VALUE = 60
	ENEMY_NEAR_OWN_HILL_SCENT_VALUE = 200
	ENEMY_AT_OWN_HILL_SCENT_VALUE = 400
